site_name:        CICOCore.jl
repo_url:         https://github.com/insysbio/CICOCore.jl
site_description: A Julia package for identifiability analysis and confidence intervals estimation.
site_author:      InSysBio

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'
